
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: ns-prometheus
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global: null
    receivers:
    - name: 'admins'
      webhook_configs:
      - url: http://prometheus-bot:9087/alert/806854305
        send_resolved: True
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: admins
      repeat_interval: 3h
