- name: Resetting kubeadm if previous instalation
  shell: kubeadm reset -f
  register: output

- name: Copying token to worker nodes
  copy: src=/home/centos/{{ token_file }} dest=/home/centos/join_token

- name: Adding worker to the cluster
  shell: |
    kubeadm reset -f
    cat /home/centos/join_token | tail -2 > out.sh
    sh out.sh
