apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pods
  labels:
    app: pods
    service: pods
spec:
  selector:
    app: pods
  ports:
    - name: http
      port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nodes
  labels:
    app: nodes
    service: nodes
spec:
  selector:
    app: nodes
  ports:
    - name: http
      port: 8000
