--- # Master
- hosts: master
  become: yes
  vars_files:
  - env_var
  roles:
    - etc_hosts
    - disable_SElinux
    - allow_netPort_firewalld
    - br_netfilter
    - enable_bridge_firewall
    - disable_swap
    - docker
    - kubernetes
    - init_cluster
    - flannel
