--- # Workers
- hosts: workers
  become: yes
  vars_files:
  - env_var
  roles:
    - etc_hosts
    - disable_SElinux
    - allow_netPort_firewalld
    - br_netfilter
    - enable_bridge_firewall
    - enable_ip_forward
    - disable_swap
    - docker
    - kubernetes
    - add_worker
