{{- /*

TODO(https://github.com/istio/istio/issues/18199) remove this configuration from charts once the operator starts managing it

*/ -}}

{{ if .Values.clusterResources }}
{{- if .Values.global.mtls.enabled }}

# Authentication policy to enable mutual TLS for all services (that have sidecar) in the mesh.
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
  labels:
    release: {{ .Release.Name }}
spec:
  peers:
  - mtls: {}
---
{{- if not .Values.global.mtls.auto }}
# Only add ISTIO_MUTUAL global destination rule when auto mtls is disabled and global mtls is enabled.
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "default"
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
# Only add ISTIO_MUTUAL global destination rule when auto mtls is disabled and global mtls is enabled.
# Destination rule to disable (m)TLS when talking to API server, as API server doesn't have sidecar.
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "api-server"
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  host: "kubernetes.default.svc.{{ .Values.global.proxy.clusterDomain }}"
  trafficPolicy:
    tls:
      mode: DISABLE
---
{{ end }}
{{- else }}
# Authentication policy to enable permissive mode for all services (that have sidecar) in the mesh.
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
  labels:
    release: {{ .Release.Name }}
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
---

{{ end }}
{{ end }}
